volumes:
  fdb_volume:

x-s3_common_depends: &s3_common_depends
  depends_on:
    - s3
    # - graphite
  links:
    - s3
    # - graphite

services:
  golang:
    build:
      dockerfile: ./docker/golang/Dockerfile
      context: .
    image: wal-g/golang
    container_name: wal-g_golang

  ubuntu:
    build:
      dockerfile: ./docker/ubuntu/Dockerfile
      context: .
    image: wal-g/ubuntu:18.04
    container_name: wal-g_ubuntu

  s3:
    image: minio/minio:RELEASE.2021-06-07T21-40-51Z
    container_name: wal-g_s3
    hostname: s3
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    entrypoint: sh
    command: >
      -c 'mkdir -p /export/fullbucket
      &&  mkdir -p /export/fullratingcomposerbucket
      &&  mkdir -p /export/fulldatabasecomposerbucket
      &&  mkdir -p /export/fullcopycomposerbucket
      &&  mkdir -p /export/fullwithoutfilesmetadatabucket
      &&  mkdir -p /export/fullscandeltabucket
      &&  mkdir -p /export/failoverstoragebucket
      &&  mkdir -p /export/partialbucket
      &&  mkdir -p /export/remotebucket
      &&  mkdir -p /export/remotewithoutfilesmetadatabucket
      &&  mkdir -p /export/cryptobucket
      &&  mkdir -p /export/waldeltabucket
      &&  mkdir -p /export/ghostbucket
      &&  mkdir -p /export/compressionbucket
      &&  mkdir -p /export/deleteretainafterbucket
      &&  mkdir -p /export/copyallbucket
      &&  mkdir -p /export/copybackupbucket
      &&  mkdir -p /export/compressionreversebucket
      &&  mkdir -p /export/delete-retain-full-bucket
      &&  mkdir -p /export/delete-retain-full-multist-bucket
      &&  mkdir -p /export/delete-retain-full-multist-fo-bucket
      &&  mkdir -p /export/delete-retain-find-full-bucket
      &&  mkdir -p /export/delete-before-name-find-full-bucket
      &&  mkdir -p /export/delete-before-time-find-full-bucket
      &&  mkdir -p /export/delete-before-permanent-full-bucket
      &&  mkdir -p /export/delete-before-permanent-delta-bucket
      &&  mkdir -p /export/delete-before-permanent-delta-multist-bucket
      &&  mkdir -p /export/delete-before-permanent-delta-multist-fo-bucket
      &&  mkdir -p /export/delete-without-confirm-bucket
      &&  mkdir -p /export/delete-end-to-end-bucket
      &&  mkdir -p /export/delete-end-to-end-fo-bucket
      &&  mkdir -p /export/delete-target-bucket
      &&  mkdir -p /export/delete-target-delta-find-full-bucket
      &&  mkdir -p /export/delete-target-delta-bucket
      &&  mkdir -p /export/delete-target-delta-multist-bucket
      &&  mkdir -p /export/delete-target-delta-multist-fo-bucket
      &&  mkdir -p /export/delete-garbage-bucket
      &&  mkdir -p /export/delete-garbage-multist-bucket
      &&  mkdir -p /export/delete-garbage-multist-fo-bucket
      &&  mkdir -p /export/gpdeletetargetbucket
      &&  mkdir -p /export/gpdeletegarbagebucket
      &&  mkdir -p /export/mysqlfullxtrabackupbucket
      &&  mkdir -p /export/mysqlincrementalxtrabackupbucket
      &&  mkdir -p /export/mysqlsplitfilesizebucket
      &&  mkdir -p /export/mysqlfullxtrabackupwithrangesbucket
      &&  mkdir -p /export/mysqlfullmysqldumpbucket
      &&  mkdir -p /export/mysqlbinlogpushfetchbucket
      &&  mkdir -p /export/mysqldeleteendtoendbucket
      &&  mkdir -p /export/mysqldeleteeverythingpermanent
      &&  mkdir -p /export/mysqldeleteincrementalxtrabackupbucket
      &&  mkdir -p /export/mysqlmarkbucket
      &&  mkdir -p /export/mysqlmarknoerrorbucket
      &&  mkdir -p /export/mysqlmarkincrementalbucket
      &&  mkdir -p /export/mysqlbinlogreplaybucket
      &&  mkdir -p /export/mysql_pitr_binlogserver_bucket
      &&  mkdir -p /export/mysqlpitrxtrabackupbucket
      &&  mkdir -p /export/mysqlpitrmysqldumpbucket
      &&  mkdir -p /export/mysqllivereplay
      &&  mkdir -p /export/mysqlpermanentbackupbucket
      &&  mkdir -p /export/mariadb_binlog_push_fetch
      &&  mkdir -p /export/mariadb_binlog_push_with_gtids_check
      &&  mkdir -p /export/mariadb_full_mysqldump
      &&  mkdir -p /export/mariadb_full_maria_backup
      &&  mkdir -p /export/mariadb_pitr_xtrabackup
      &&  mkdir -p /export/mongostreampushbucket
      &&  mkdir -p /export/mongooplogpushbucket
      &&  mkdir -p /export/mongodeletebeforebucket
      &&  mkdir -p /export/mongodeleteretainbucket
      &&  mkdir -p /export/redisbucket
      &&  mkdir -p /export/mysqlcopybackupfrom
      &&  mkdir -p /export/mysqlcopybackupto
      &&  mkdir -p /export/mysqlconfonly
      &&  mkdir -p /export/mysqldeletebinlogs
      &&  mkdir -p /export/archivereadyrename
      &&  mkdir -p /export/gpfullbucket
      &&  mkdir -p /export/gpafterfailedbucket
      &&  mkdir -p /export/gpfullserializedbucket
      &&  mkdir -p /export/gpdeletewithoutconfirm
      &&  mkdir -p /export/gpdeleteretainbucket
      &&  mkdir -p /export/gpdeleteendtoendbucket
      &&  mkdir -p /export/gpdeletebeforepermanentbucket
      &&  mkdir -p /export/gpdeletebeforenamebucket
      &&  mkdir -p /export/gpdeletebeforetimebucket
      &&  mkdir -p /export/gpaostoragetestbucket
      &&  mkdir -p /export/gpdeltabackuptestbucket
      &&  mkdir -p /export/gppartialdatabasebucket
      &&  mkdir -p /export/gppartialtablebucket
      &&  mkdir -p /export/createrestorepointbucket
      &&  mkdir -p /export/storagetoolsbucket
      &&  mkdir -p /export/storagetoolsbucket_target
      &&  mkdir -p /export/sttransferfilesbucket
      &&  mkdir -p /export/sttransferfilesfailoverbucket
      &&  mkdir -p /export/transferbackupbucket
      &&  mkdir -p /export/walrestorebucket
      &&  mkdir -p /export/daemonbucket
      &&  mkdir -p /export/backupmarkimpermanentbucket
      &&  mkdir -p /export/backupmarkpermanentnoerrorbucket
      &&  mkdir -p /export/backupmarkpermanentbucket
      &&  mkdir -p /export/backupperftestbucket
      &&  mkdir -p /export/catchupbucket
      &&  mkdir -p /export/fullstreamedbucket
      &&  mkdir -p /export/receivewalbucket
      &&  mkdir -p /export/severaldeltabackupsbucket
      &&  mkdir -p /export/walperftestbucket
      &&  /usr/bin/minio server /export'

  pg:
    build:
      dockerfile: docker/pg/Dockerfile
      context: .
    image: wal-g/pg
    container_name: wal-g_pg

  pg_build_docker_prefix:
    build:
      dockerfile: docker/pg_tests/Dockerfile_prefix
      context: .
    image: wal-g/docker_prefix
    container_name: wal-g_pg_docker_prefix

  pg_test_common: &pg_test_common
    image: wal-g/docker_prefix
    user: postgres
    <<: *s3_common_depends

  pg_delete_before_permanent_delta_test:
    <<: *pg_test_common
    container_name: wal-g_pg_delete_before_permanent_delta_test
    command: /tmp/tests/delete_before_permanent_delta_test.sh
